create table "public"."license" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "type" text not null,
    "url" text not null
);


alter table "public"."license" enable row level security;

CREATE UNIQUE INDEX license_pkey ON public.license USING btree (id);

alter table "public"."license" add constraint "license_pkey" PRIMARY KEY using index "license_pkey";

grant delete on table "public"."license" to "anon";

grant insert on table "public"."license" to "anon";

grant references on table "public"."license" to "anon";

grant select on table "public"."license" to "anon";

grant trigger on table "public"."license" to "anon";

grant truncate on table "public"."license" to "anon";

grant update on table "public"."license" to "anon";

grant delete on table "public"."license" to "authenticated";

grant insert on table "public"."license" to "authenticated";

grant references on table "public"."license" to "authenticated";

grant select on table "public"."license" to "authenticated";

grant trigger on table "public"."license" to "authenticated";

grant truncate on table "public"."license" to "authenticated";

grant update on table "public"."license" to "authenticated";

grant delete on table "public"."license" to "service_role";

grant insert on table "public"."license" to "service_role";

grant references on table "public"."license" to "service_role";

grant select on table "public"."license" to "service_role";

grant trigger on table "public"."license" to "service_role";

grant truncate on table "public"."license" to "service_role";

grant update on table "public"."license" to "service_role";


