create table "public"."icon" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null,
    "version" text not null,
    "name" text,
    "svg" text,
    "source_url" text,
    "provider_id" bigint not null
);

alter table "public"."icon" enable row level security;

create table "public"."provider" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" text,
    "git_branch" text,
    "git_icons_dir" text,
    "git_url" text
);

alter table "public"."provider" enable row level security;

CREATE UNIQUE INDEX icon_pkey ON public.icon USING btree (id);

CREATE UNIQUE INDEX provider_pkey ON public.provider USING btree (id);

alter table "public"."icon" add constraint "icon_pkey" PRIMARY KEY using index "icon_pkey";

alter table "public"."provider" add constraint "provider_pkey" PRIMARY KEY using index "provider_pkey";

alter table "public"."icon" add constraint "icon_provider_id_fkey" FOREIGN KEY (provider_id) REFERENCES provider(id) not valid;

alter table "public"."icon" validate constraint "icon_provider_id_fkey";

grant delete on table "public"."icon" to "anon";

grant insert on table "public"."icon" to "anon";

grant references on table "public"."icon" to "anon";

grant select on table "public"."icon" to "anon";

grant trigger on table "public"."icon" to "anon";

grant truncate on table "public"."icon" to "anon";

grant update on table "public"."icon" to "anon";

grant delete on table "public"."icon" to "authenticated";

grant insert on table "public"."icon" to "authenticated";

grant references on table "public"."icon" to "authenticated";

grant select on table "public"."icon" to "authenticated";

grant trigger on table "public"."icon" to "authenticated";

grant truncate on table "public"."icon" to "authenticated";

grant update on table "public"."icon" to "authenticated";

grant delete on table "public"."icon" to "service_role";

grant insert on table "public"."icon" to "service_role";

grant references on table "public"."icon" to "service_role";

grant select on table "public"."icon" to "service_role";

grant trigger on table "public"."icon" to "service_role";

grant truncate on table "public"."icon" to "service_role";

grant update on table "public"."icon" to "service_role";

grant delete on table "public"."provider" to "anon";

grant insert on table "public"."provider" to "anon";

grant references on table "public"."provider" to "anon";

grant select on table "public"."provider" to "anon";

grant trigger on table "public"."provider" to "anon";

grant truncate on table "public"."provider" to "anon";

grant update on table "public"."provider" to "anon";

grant delete on table "public"."provider" to "authenticated";

grant insert on table "public"."provider" to "authenticated";

grant references on table "public"."provider" to "authenticated";

grant select on table "public"."provider" to "authenticated";

grant trigger on table "public"."provider" to "authenticated";

grant truncate on table "public"."provider" to "authenticated";

grant update on table "public"."provider" to "authenticated";

grant delete on table "public"."provider" to "service_role";

grant insert on table "public"."provider" to "service_role";

grant references on table "public"."provider" to "service_role";

grant select on table "public"."provider" to "service_role";

grant trigger on table "public"."provider" to "service_role";

grant truncate on table "public"."provider" to "service_role";

grant update on table "public"."provider" to "service_role";
